version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ctrlpy
  redis:
    image: redis:6.2-alpine
    command: redis-server
    ports:
      - "6379:6379"
